package me.rerere.workspace

import java.io.File

class RootfsPatcher {
    private val filesFactory: RootfsPatchFilesFactory

    constructor() {
        filesFactory = NativeRootfsPatchFilesFactory
    }

    internal constructor(filesFactory: RootfsPatchFilesFactory) {
        this.filesFactory = filesFactory
    }

    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        requireValidOptions(options)
        val files = filesFactory.open(linuxDir) ?: return
        if (!files.directory("etc", create = false)) return

        ensureRootfsDns(files, options.nameservers)
        ensureHosts(files, options.hostname)
        ensureHostname(files, options.hostname)
        ensureLocale(files, options.locale)
        ensureGroupNames(files, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        ensureTempDirs(files)
        ensureExecutionMountPoints(files)
    }

    private fun ensureRootfsDns(
        files: RootfsPatchFiles,
        nameservers: List<String>,
    ) {
        val resolvConf = files.fileKind("etc/resolv.conf", allowLeafSymlink = true)
        val shouldWrite = when (resolvConf) {
            null, RootfsPatchFileKind.SYMLINK -> true
            RootfsPatchFileKind.REGULAR -> files.readText("etc/resolv.conf")
                .lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .none { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in LOCAL_RESOLVERS
                }
        }
        if (!shouldWrite) return

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }

        files.writeText(
            relativePath = "etc/resolv.conf",
            replaceLeafSymlink = true,
            text = buildString {
                appendLine("# Generated by Miffan workspace.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            },
        )
    }

    private fun ensureHosts(files: RootfsPatchFiles, hostname: String) {
        val original = files.readTextIfExists("etc/hosts").orEmpty()
        val lines = original.lineSequence().toList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        files.writeText(
            relativePath = "etc/hosts",
            text = buildString {
                append(original)
                if (original.isNotEmpty() && !original.endsWith('\n')) appendLine()
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            },
        )
    }

    private fun ensureHostname(files: RootfsPatchFiles, hostname: String) {
        val existing = files.readTextIfExists("etc/hostname")
        if (!existing.isNullOrBlank()) return
        files.writeText("etc/hostname", "${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(files: RootfsPatchFiles, locale: String) {
        files.directory("etc/default", create = true)
        val original = files.readTextIfExists("etc/default/locale").orEmpty()
        if (original.lineSequence().any { it.trim().startsWith("LANG=") }) return
        files.writeText(
            relativePath = "etc/default/locale",
            text = buildString {
                append(original)
                if (original.isNotEmpty() && !original.endsWith('\n')) appendLine()
                appendLine("LANG=$locale")
            },
        )
    }

    private fun ensureGroupNames(files: RootfsPatchFiles, groupIds: List<Long>) {
        val existingGroup = files.fileKind("etc/group")
        val original = existingGroup?.let { files.readText("etc/group") } ?: "root:x:0:\n"
        val lines = original.lineSequence().toList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty() && existingGroup != null) return

        files.writeText(
            relativePath = "etc/group",
            text = buildString {
                append(original)
                if (original.isNotEmpty() && !original.endsWith('\n')) appendLine()
                additions.forEach { appendLine(it) }
            },
        )
    }

    private fun ensureTempDirs(files: RootfsPatchFiles) {
        listOf("tmp", "var/tmp").forEach { guestPath ->
            check(files.directory(guestPath, create = true)) {
                "Unable to create /$guestPath"
            }
            files.chmodDirectory(guestPath, GUEST_TEMP_DIRECTORY_MODE)
        }
        check(files.directory("root", create = true)) { "Unable to create /root" }
        files.chmodDirectory("root", GUEST_ROOT_DIRECTORY_MODE)
    }

    fun repairExecutionMountPoints(linuxDir: File) {
        val files = filesFactory.open(linuxDir) ?: return
        ensureExecutionMountPoints(files)
    }

    private fun ensureExecutionMountPoints(files: RootfsPatchFiles) {
        EXECUTION_MOUNT_POINTS.forEach { (guestPath, mode) ->
            check(files.directory(guestPath, create = true)) {
                "Unable to create /$guestPath"
            }
            files.chmodDirectory(guestPath, mode)
        }
    }

    private fun requireValidOptions(options: RootfsPatchOptions) {
        require(
            options.hostname.isBlank() ||
                options.hostname.matches(Regex("[A-Za-z0-9][A-Za-z0-9.-]{0,252}"))
        ) { "Rootfs hostname contains invalid characters" }
        require(options.locale.matches(Regex("[A-Za-z0-9][A-Za-z0-9._@-]{0,127}"))) {
            "Rootfs locale contains invalid characters"
        }
        require(options.nameservers.size <= MAX_OPTION_VALUES) { "Too many Rootfs nameservers" }
        options.nameservers.filter { it.isNotBlank() }.forEach { server ->
            require(server.matches(Regex("[A-Za-z0-9:.%_-]{1,255}"))) {
                "Rootfs nameserver contains invalid characters"
            }
        }
        require(options.groupIds.size <= MAX_OPTION_VALUES) { "Too many Rootfs group ids" }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val MAX_DNS_SERVERS = 3
        private const val MAX_OPTION_VALUES = 1024
        private const val GUEST_TEMP_DIRECTORY_MODE = 0b1_111_111_111
        private const val GUEST_ROOT_DIRECTORY_MODE = 0b111_000_000
        private const val GUEST_MOUNT_DIRECTORY_MODE = 0b111_101_101
        private const val GUEST_WORKSPACE_DIRECTORY_MODE = 0b111_000_000
        private val EXECUTION_MOUNT_POINTS = listOf(
            "workspace" to GUEST_WORKSPACE_DIRECTORY_MODE,
            "dev" to GUEST_MOUNT_DIRECTORY_MODE,
            "proc" to GUEST_MOUNT_DIRECTORY_MODE,
            "sys" to GUEST_MOUNT_DIRECTORY_MODE,
        )
        private const val DEFAULT_HOSTNAME = "localhost"
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )
        private val DEFAULT_DNS_SERVERS = listOf(
            "1.1.1.1",
            "8.8.8.8",
            "223.5.5.5",
        )
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
)
