package me.rerere.workspace

import java.io.ByteArrayOutputStream
import java.io.File
import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets
import java.nio.file.FileAlreadyExistsException
import java.nio.file.Files
import java.nio.file.LinkOption
import java.nio.file.OpenOption
import java.nio.file.Path
import java.nio.file.StandardOpenOption

class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        requireValidOptions(options)
        val files = RootfsPatchFiles.open(linuxDir) ?: return
        if (files.directory("etc", create = false) == null) return

        ensureRootfsDns(files, options.nameservers)
        ensureHosts(files, options.hostname)
        ensureHostname(files, options.hostname)
        ensureLocale(files, options.locale)
        ensureGroupNames(files, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        ensureTempDirs(files)
    }

    private fun ensureRootfsDns(
        files: RootfsPatchFiles,
        nameservers: List<String>,
    ) {
        val resolvConf = files.inspectFile("etc/resolv.conf", allowLeafSymlink = true)
        val shouldWrite = when {
            resolvConf == null -> true
            Files.isSymbolicLink(resolvConf) -> true
            else -> files.readText(resolvConf)
                .lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .none { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in LOCAL_RESOLVERS
                }
        }
        if (!shouldWrite) return

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }

        files.writeText(
            relativePath = "etc/resolv.conf",
            replaceLeafSymlink = true,
            text = buildString {
                appendLine("# Generated by RikkaHub workspace.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            },
        )
    }

    private fun ensureHosts(files: RootfsPatchFiles, hostname: String) {
        val original = files.readTextIfExists("etc/hosts").orEmpty()
        val lines = original.lineSequence().toList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        files.writeText(
            relativePath = "etc/hosts",
            text = buildString {
                append(original)
                if (original.isNotEmpty() && !original.endsWith('\n')) appendLine()
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            },
        )
    }

    private fun ensureHostname(files: RootfsPatchFiles, hostname: String) {
        val existing = files.readTextIfExists("etc/hostname")
        if (!existing.isNullOrBlank()) return
        files.writeText("etc/hostname", "${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(files: RootfsPatchFiles, locale: String) {
        files.directory("etc/default", create = true)
        val original = files.readTextIfExists("etc/default/locale").orEmpty()
        if (original.lineSequence().any { it.trim().startsWith("LANG=") }) return
        files.writeText(
            relativePath = "etc/default/locale",
            text = buildString {
                append(original)
                if (original.isNotEmpty() && !original.endsWith('\n')) appendLine()
                appendLine("LANG=$locale")
            },
        )
    }

    private fun ensureGroupNames(files: RootfsPatchFiles, groupIds: List<Long>) {
        val existingGroup = files.inspectFile("etc/group")
        val original = existingGroup?.let(files::readText) ?: "root:x:0:\n"
        val lines = original.lineSequence().toList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty() && existingGroup != null) return

        files.writeText(
            relativePath = "etc/group",
            text = buildString {
                append(original)
                if (original.isNotEmpty() && !original.endsWith('\n')) appendLine()
                additions.forEach { appendLine(it) }
            },
        )
    }

    @Suppress("SetWorldReadable", "SetWorldWritable")
    private fun ensureTempDirs(files: RootfsPatchFiles) {
        val tempDirs = listOf("tmp", "var/tmp").map { path ->
            path to requireNotNull(files.directory(path, create = true))
        }
        val rootDir = requireNotNull(files.directory("root", create = true))
        tempDirs.forEach { (guestPath, path) ->
            val dir = path.toFile()
            require(dir.setReadable(true, false)) { "Unable to make /$guestPath readable" }
            require(dir.setWritable(true, false)) { "Unable to make /$guestPath writable" }
            require(dir.setExecutable(true, false)) { "Unable to make /$guestPath executable" }
        }
        rootDir.toFile().apply {
            require(setReadable(true, true)) { "Unable to make /root readable" }
            require(setWritable(true, true)) { "Unable to make /root writable" }
            require(setExecutable(true, true)) { "Unable to make /root executable" }
        }
    }

    private fun requireValidOptions(options: RootfsPatchOptions) {
        require(
            options.hostname.isBlank() ||
                options.hostname.matches(Regex("[A-Za-z0-9][A-Za-z0-9.-]{0,252}"))
        ) { "Rootfs hostname contains invalid characters" }
        require(options.locale.matches(Regex("[A-Za-z0-9][A-Za-z0-9._@-]{0,127}"))) {
            "Rootfs locale contains invalid characters"
        }
        require(options.nameservers.size <= MAX_OPTION_VALUES) { "Too many Rootfs nameservers" }
        options.nameservers.filter { it.isNotBlank() }.forEach { server ->
            require(server.matches(Regex("[A-Za-z0-9:.%_-]{1,255}"))) {
                "Rootfs nameserver contains invalid characters"
            }
        }
        require(options.groupIds.size <= MAX_OPTION_VALUES) { "Too many Rootfs group ids" }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val MAX_DNS_SERVERS = 3
        private const val MAX_OPTION_VALUES = 1024
        private const val DEFAULT_HOSTNAME = "localhost"
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )
        private val DEFAULT_DNS_SERVERS = listOf(
            "1.1.1.1",
            "8.8.8.8",
            "223.5.5.5",
        )
    }
}

private class RootfsPatchFiles private constructor(
    private val root: Path,
) {
    fun directory(relativePath: String, create: Boolean): Path? {
        var current = root
        for (segment in segments(relativePath)) {
            current = current.resolve(segment)
            if (!Files.exists(current, LinkOption.NOFOLLOW_LINKS)) {
                if (!create) return null
                try {
                    Files.createDirectory(current)
                } catch (_: FileAlreadyExistsException) {
                    // Re-check below: a concurrent symlink replacement must not be accepted.
                }
            }
            require(Files.isDirectory(current, LinkOption.NOFOLLOW_LINKS)) {
                "Refusing Rootfs host access through symbolic link or non-directory: /$relativePath"
            }
        }
        return current
    }

    fun inspectFile(relativePath: String, allowLeafSymlink: Boolean = false): Path? {
        val segments = segments(relativePath)
        require(segments.isNotEmpty()) { "Rootfs maintenance path must identify a file" }
        val parent = directory(segments.dropLast(1).joinToString("/"), create = false) ?: return null
        val target = parent.resolve(segments.last())
        if (!Files.exists(target, LinkOption.NOFOLLOW_LINKS)) return null
        if (Files.isSymbolicLink(target)) {
            require(allowLeafSymlink) {
                "Refusing Rootfs host access through symbolic link: /$relativePath"
            }
        } else {
            require(Files.isRegularFile(target, LinkOption.NOFOLLOW_LINKS)) {
                "Rootfs maintenance path is not a regular file: /$relativePath"
            }
        }
        return target
    }

    fun readTextIfExists(relativePath: String): String? =
        inspectFile(relativePath)?.let(::readText)

    fun readText(path: Path): String {
        val output = ByteArrayOutputStream()
        val buffer = ByteBuffer.allocate(DEFAULT_BUFFER_SIZE)
        Files.newByteChannel(
            path,
            setOf<OpenOption>(StandardOpenOption.READ, LinkOption.NOFOLLOW_LINKS),
        ).use { channel ->
            while (true) {
                val read = channel.read(buffer)
                if (read < 0) break
                if (read == 0) continue
                require(output.size().toLong() + read <= MAX_MAINTENANCE_FILE_BYTES) {
                    "Rootfs maintenance file is too large: $path"
                }
                output.write(buffer.array(), 0, read)
                buffer.clear()
            }
        }
        return output.toString(StandardCharsets.UTF_8.name())
    }

    fun writeText(
        relativePath: String,
        text: String,
        replaceLeafSymlink: Boolean = false,
    ) {
        val bytes = text.toByteArray(StandardCharsets.UTF_8)
        require(bytes.size <= MAX_MAINTENANCE_FILE_BYTES) {
            "Rootfs maintenance file is too large: /$relativePath"
        }
        val segments = segments(relativePath)
        require(segments.isNotEmpty()) { "Rootfs maintenance path must identify a file" }
        val parent = requireNotNull(
            directory(segments.dropLast(1).joinToString("/"), create = true)
        )
        val target = parent.resolve(segments.last())
        if (Files.exists(target, LinkOption.NOFOLLOW_LINKS)) {
            if (Files.isSymbolicLink(target)) {
                require(replaceLeafSymlink) {
                    "Refusing Rootfs host access through symbolic link: /$relativePath"
                }
                Files.delete(target)
            } else {
                require(Files.isRegularFile(target, LinkOption.NOFOLLOW_LINKS)) {
                    "Rootfs maintenance path is not a regular file: /$relativePath"
                }
            }
        }

        Files.newByteChannel(
            target,
            setOf<OpenOption>(
                StandardOpenOption.WRITE,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING,
                LinkOption.NOFOLLOW_LINKS,
            ),
        ).use { channel ->
            val buffer = ByteBuffer.wrap(bytes)
            while (buffer.hasRemaining()) channel.write(buffer)
        }
    }

    private fun segments(relativePath: String): List<String> {
        if (relativePath.isBlank()) return emptyList()
        require(!relativePath.startsWith('/') && !relativePath.contains('\\')) {
            "Rootfs maintenance path must be relative"
        }
        return relativePath.split('/').also { segments ->
            require(segments.none { it.isBlank() || it == "." || it == ".." }) {
                "Rootfs maintenance path is ambiguous"
            }
        }
    }

    companion object {
        private const val MAX_MAINTENANCE_FILE_BYTES = 256 * 1024

        fun open(root: File): RootfsPatchFiles? {
            val path = root.toPath().toAbsolutePath().normalize()
            if (!Files.exists(path, LinkOption.NOFOLLOW_LINKS)) return null
            require(Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS)) {
                "Rootfs directory must not be a symbolic link"
            }
            return RootfsPatchFiles(path)
        }
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
)
